-- ============================================================
-- HDT-003 - Tabla de auditoria de eventos del sistema
-- Base de datos: PostgreSQL 18
-- ============================================================

CREATE TABLE IF NOT EXISTS auditoria_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tipo_evento VARCHAR(50) NOT NULL,
    entidad VARCHAR(100),
    entidad_id BIGINT,
    accion VARCHAR(50) NOT NULL,

    usuario_id BIGINT,
    usuario_nombre VARCHAR(200),

    detalle TEXT,
    direccion_ip VARCHAR(50),

    fecha_evento TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_tipo
ON auditoria_eventos(tipo_evento);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_entidad
ON auditoria_eventos(entidad, entidad_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_usuario
ON auditoria_eventos(usuario_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_fecha
ON auditoria_eventos(fecha_evento DESC);

COMMENT ON TABLE auditoria_eventos IS 'Registro de auditoría de eventos del sistema';
COMMENT ON COLUMN auditoria_eventos.tipo_evento IS 'Tipo: LOGIN, LOGOUT, CREATE, UPDATE, DELETE, ERROR';
COMMENT ON COLUMN auditoria_eventos.entidad IS 'Nombre de la entidad afectada (ej: Usuario, Equipo, Averia)';
COMMENT ON COLUMN auditoria_eventos.entidad_id IS 'ID de la entidad afectada';
COMMENT ON COLUMN auditoria_eventos.accion IS 'Acción realizada (ej: CREAR, ACTUALIZAR, ELIMINAR, INICIAR_SESION)';
