ALTER TABLE fac_equipos
    ADD COLUMN IF NOT EXISTS fecha_ingreso DATE,
    ADD COLUMN IF NOT EXISTS numero_guia_remision VARCHAR(100),
    ADD COLUMN IF NOT EXISTS ingreso_completo BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE fac_equipos
SET fecha_ingreso = COALESCE(fecha_ingreso, fecha_creacion::date),
    ingreso_completo = TRUE
WHERE fecha_ingreso IS NULL OR ingreso_completo IS NULL;

CREATE TABLE IF NOT EXISTS fac_evidencias_ingreso_equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id BIGINT NOT NULL REFERENCES fac_equipos(id) ON DELETE CASCADE,
    tipo VARCHAR(40) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(100) NOT NULL,
    tamanio_bytes BIGINT NOT NULL,
    contenido BYTEA NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion BIGINT,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_actualizacion BIGINT,
    CONSTRAINT uq_evidencia_ingreso_equipo_tipo UNIQUE (equipo_id, tipo),
    CONSTRAINT chk_evidencia_ingreso_tipo CHECK (tipo IN (
        'LATERAL_IZQUIERDO','LATERAL_DERECHO','FRONTAL','POSTERIOR',
        'BATERIA_1','BATERIA_2','CONO','BOTIQUIN','CARGADOR',
        'TRANSFORMADOR','CABLE_ADICIONAL','MESA_RODILLOS',
        'ELEVADOR_BATERIA','CONECTOR_ADICIONAL','GUIA_REMISION',
        'DETALLE_1','DETALLE_2','DETALLE_3'
    )),
    CONSTRAINT chk_evidencia_ingreso_tamanio CHECK (
        tamanio_bytes > 0 AND tamanio_bytes <= 5242880
    )
);

CREATE INDEX IF NOT EXISTS idx_evidencia_ingreso_equipo
ON fac_evidencias_ingreso_equipo(equipo_id);

CREATE INDEX IF NOT EXISTS idx_equipo_ingreso_completo
ON fac_equipos(ingreso_completo);
