-- ============================================================
-- V20 - Finalización del Servicio (devolución de equipos)
-- Agrega fecha_devolucion + estado DEVUELTO + evidencias de devolución
-- ============================================================

ALTER TABLE fac_equipos
    ADD COLUMN IF NOT EXISTS fecha_devolucion TIMESTAMP WITH TIME ZONE;

ALTER TABLE fac_equipos
    DROP CONSTRAINT IF EXISTS chk_estado_operativo_equipo;

ALTER TABLE fac_equipos
    ADD CONSTRAINT chk_estado_operativo_equipo
    CHECK (estado_operativo IN ('OPERATIVO','AVERIADO','DEVUELTO'));

CREATE TABLE IF NOT EXISTS fac_evidencias_devolucion_equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id BIGINT NOT NULL REFERENCES fac_equipos(id) ON DELETE CASCADE,
    tipo VARCHAR(40) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(100) NOT NULL,
    tamanio_bytes BIGINT NOT NULL,
    contenido BYTEA NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion BIGINT,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_actualizacion BIGINT,
    CONSTRAINT uq_evidencia_devolucion_equipo_tipo UNIQUE (equipo_id, tipo),
    CONSTRAINT chk_evidencia_devolucion_tipo CHECK (tipo IN (
        'DEVOLUCION_FRONTAL',
        'DEVOLUCION_LATERAL_IZQUIERDO',
        'DEVOLUCION_LATERAL_DERECHO',
        'DEVOLUCION_POSTERIOR'
    )),
    CONSTRAINT chk_evidencia_devolucion_tamanio CHECK (
        tamanio_bytes > 0 AND tamanio_bytes <= 5242880
    )
);

CREATE INDEX IF NOT EXISTS idx_evidencia_devolucion_equipo
ON fac_evidencias_devolucion_equipo(equipo_id);

CREATE INDEX IF NOT EXISTS idx_equipo_fecha_devolucion
ON fac_equipos(fecha_devolucion);
