-- ============================================================
-- HDT-002 - Catálogos operativos de equipos
-- Base de datos: PostgreSQL 18
-- ============================================================

CREATE TABLE IF NOT EXISTS dim_tipos_equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dim_proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_social VARCHAR(255) NOT NULL UNIQUE,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    ruc VARCHAR(20),
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dim_marcas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_dim_tipos_equipo_estado ON dim_tipos_equipo(estado_activo);
CREATE INDEX IF NOT EXISTS idx_dim_proveedores_estado ON dim_proveedores(estado_activo);
CREATE INDEX IF NOT EXISTS idx_dim_marcas_estado ON dim_marcas(estado_activo);

-- Seeds oficiales HDT-002
INSERT INTO dim_tipos_equipo (nombre, codigo, usuario_creacion) VALUES
('Transpaleta - litio', 'TRANSPALETA_LITIO', 1),
('Transpaleta - plomo', 'TRANSPALETA_PLOMO', 1),
('Apilador - litio', 'APILADOR_LITIO', 1),
('Apilador - plomo', 'APILADOR_PLOMO', 1),
('Montacargas - litio', 'MONTACARGAS_LITIO', 1),
('Montacargas - plomo', 'MONTACARGAS_PLOMO', 1)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO dim_proveedores (razon_social, codigo, usuario_creacion) VALUES
('DERCO PERÚ SA', 'DERCO_PERU_SA', 1),
('HIDRA RYL SAC', 'HIDRA_RYL_SAC', 1),
('MATIV SAC', 'MATIV_SAC', 1),
('RD RENTAL SAC', 'RD_RENTAL_SAC', 1),
('MAQUISERVICES M&E SAC', 'MAQUISERVICES_ME_SAC', 1),
('TECNOLOGÍA MECATRÓNICA DELWI SAC', 'TECNOLOGIA_MECATRONICA_DELWI_SAC', 1),
('TRITON TRADING SA', 'TRITON_TRADING_SA', 1),
('LINDE HIGH LIFT PERÚ SAC', 'LINDE_HIGH_LIFT_PERU_SAC', 1),
('ZAPLER SAC', 'ZAPLER_SAC', 1)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO dim_marcas (nombre, codigo, usuario_creacion) VALUES
('Linde', 'LINDE', 1),
('Hangcha', 'HANGCHA', 1),
('Caterpillar', 'CATERPILLAR', 1),
('Still', 'STILL', 1),
('Komatsu', 'KOMATSU', 1),
('Crown', 'CROWN', 1),
('Jungheinrich', 'JUNGHEINRICH', 1),
('Zoomlion', 'ZOOMLION', 1),
('Toyota', 'TOYOTA', 1),
('Yale', 'YALE', 1),
('Malvex', 'MALVEX', 1),
('Noblefit', 'NOBLEFIT', 1)
ON CONFLICT (codigo) DO NOTHING;
