-- ============================================================
-- HDT-002 - Tabla operativa de equipos
-- Base de datos: PostgreSQL 18
-- Depende de: V4__crear_catalogos_equipos.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS fac_equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    proveedor_id BIGINT NOT NULL REFERENCES dim_proveedores(id),
    marca_id BIGINT NOT NULL