-- ============================================================
-- HDT-002 - Tabla operativa de equipos
-- Base de datos: PostgreSQL 18
-- ============================================================

CREATE TABLE IF NOT EXISTS fac_equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL REFERENCES dim_proveedores(id),
    marca_id BIGINT NOT NULL REFERENCES dim_marcas(id),
    tipo_equipo_id BIGINT NOT NULL REFERENCES dim_tipos_equipo(id),

    modelo VARCHAR(150) NOT NULL,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    numero_serie VARCHAR(150) NOT NULL UNIQUE,

    capacidad VARCHAR(50),
    altura_maxima VARCHAR(50),

    bateria BOOLEAN NOT NULL DEFAULT FALSE,
    serie_bateria VARCHAR(150),

    bateria_adicional BOOLEAN NOT NULL DEFAULT FALSE,
    serie_bateria_adicional VARCHAR(150),

    cargador BOOLEAN NOT NULL DEFAULT FALSE,
    serie_cargador VARCHAR(150),

    transformador BOOLEAN NOT NULL DEFAULT FALSE,
    serie_transformador VARCHAR(150),

    extintor BOOLEAN NOT NULL DEFAULT FALSE,
    cono_seguridad BOOLEAN NOT NULL DEFAULT FALSE,
    botiquin BOOLEAN NOT NULL DEFAULT FALSE,
    mesa_rodillos BOOLEAN NOT NULL DEFAULT FALSE,
    elevador_bateria BOOLEAN NOT NULL DEFAULT FALSE,
    cable_adicional BOOLEAN NOT NULL DEFAULT FALSE,
    conector_adicional BOOLEAN NOT NULL DEFAULT FALSE,

    horometro_inicio NUMERIC(12,2),
    horometro_fin NUMERIC(12,2),

    estado_operativo VARCHAR(30) NOT NULL DEFAULT 'OPERATIVO',
    observaciones TEXT,

    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_estado_operativo_equipo
    CHECK (estado_operativo IN ('OPERATIVO','AVERIADO')),

    CONSTRAINT chk_horometros
    CHECK (
        horometro_fin IS NULL
        OR horometro_inicio IS NULL
        OR horometro_fin >= horometro_inicio
    )
);

CREATE INDEX IF NOT EXISTS idx_fac_equipos_proveedor
ON fac_equipos(proveedor_id);

CREATE INDEX IF NOT EXISTS idx_fac_equipos_marca
ON fac_equipos(marca_id);

CREATE INDEX IF NOT EXISTS idx_fac_equipos_tipo
ON fac_equipos(tipo_equipo_id);

CREATE INDEX IF NOT EXISTS idx_fac_equipos_estado
ON fac_equipos(estado_operativo);

CREATE INDEX IF NOT EXISTS idx_fac_equipos_activo
ON fac_equipos(estado_activo);