-- ============================================================
-- HDT-002 - Registro manual de PSR y OSR
-- Base de datos: PostgreSQL 18
-- Nota: no existe conexion con NISIRA.
-- Los datos son registrados manualmente por usuarios autorizados.
-- ============================================================

CREATE TABLE IF NOT EXISTS fac_psr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    campana_id BIGINT NOT NULL REFERENCES dim_campanas(id),
    sede_id BIGINT NOT NULL REFERENCES dim_sedes(id),

    numero_psr VARCHAR(100) NOT NULL UNIQUE,
    fecha_psr DATE NOT NULL,

    observaciones TEXT,

    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,

    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS fac_osr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    psr_id BIGINT NOT NULL UNIQUE REFERENCES fac_psr(id),
    equipo_id BIGINT NOT NULL REFERENCES fac_equipos(id),

    numero_osr VARCHAR(100) NOT NULL UNIQUE,
    fecha_osr DATE NOT NULL,

    observaciones TEXT,

    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,

    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_fac_psr_campana
ON fac_psr(campana_id);

CREATE INDEX IF NOT EXISTS idx_fac_psr_sede
ON fac_psr(sede_id);

CREATE INDEX IF NOT EXISTS idx_fac_osr_psr
ON fac_osr(psr_id);

CREATE INDEX IF NOT EXISTS idx_fac_osr_equipo
ON fac_osr(equipo_id);