-- ============================================================
-- HDT-002 - Registro manual de PSR y OSR
-- Base de datos: PostgreSQL 18
-- Nota: no existe conexion con NISIRA. Los datos son ingresados manualmente.
-- ============================================================

CREATE TABLE IF NOT EXISTS fac_psr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campana_id BIGINT NOT NULL REFERENCES dim_campanas(id),
    sede