-- ============================================================
-- HDT-002 - Registro de averias y evidencias fotograficas
-- Base de datos: PostgreSQL 18
-- Nota: no se usa catalogo de tipos de averia.
-- La falla se registra mediante descripcion libre.
-- ============================================================

CREATE TABLE IF NOT EXISTS fac_averias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

