-- ============================================================
-- HDT-002 - Registro de averias y evidencias fotograficas
-- Base de datos: PostgreSQL 18
-- Nota: no se usa catalogo de tipos de averia.
-- La falla se registra mediante descripcion libre.
-- ============================================================

CREATE TABLE IF NOT EXISTS fac_averias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    equipo_id BIGINT NOT NULL REFERENCES fac_equipos(id),

    descripcion_falla TEXT NOT NULL,

    fecha_hora_averia TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_hora_atencion TIMESTAMP WITH TIME ZONE,

    accion_realizada TEXT,
    dias_inactividad INTEGER,

    estado_averia VARCHAR(30) NOT NULL DEFAULT 'REPORTADA',

    observaciones TEXT,

    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,

    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_estado_averia
    CHECK (estado_averia IN ('REPORTADA','ATENDIDA')),

    CONSTRAINT chk_fechas_averia
    CHECK (
        fecha_hora_atencion IS NULL
        OR fecha_hora_atencion >= fecha_hora_averia
    ),

    CONSTRAINT chk_dias_inactividad
    CHECK (dias_inactividad IS NULL OR dias_inactividad >= 0)
);

CREATE TABLE IF NOT EXISTS fac_evidencias_averias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    averia_id BIGINT NOT NULL REFERENCES fac_averias(id) ON DELETE CASCADE,

    numero_foto SMALLINT NOT NULL,

    nombre_archivo VARCHAR(255) NOT NULL,
    ruta_archivo VARCHAR(500) NOT NULL,
    tipo_mime VARCHAR(100),
    tamanio_bytes BIGINT,

    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion BIGINT,

    CONSTRAINT chk_numero_foto_averia
    CHECK (numero_foto BETWEEN 1 AND 3),

    CONSTRAINT uq_averia_numero_foto
    UNIQUE (averia_id, numero_foto)
);

CREATE INDEX IF NOT EXISTS idx_fac_averias_equipo
ON fac_averias(equipo_id);

CREATE INDEX IF NOT EXISTS idx_fac_averias_fecha
ON fac_averias(fecha_hora_averia);

CREATE INDEX IF NOT EXISTS idx_fac_averias_estado
ON fac_averias(estado_averia);

CREATE INDEX IF NOT EXISTS idx_fac_averias_activo
ON fac_averias(estado_activo);

CREATE INDEX IF NOT EXISTS idx_fac_evidencias_averias_averia
ON fac_evidencias_averias(averia_id);