package com.apilamiento.control.entity;

public enum TipoEvidenciaDevolucion {
    DEVOLUCION_FRONTAL,
    DEVOLUCION_LATERAL_IZQUIERDO,
    DEVOLUCION_LATERAL_DERECHO,
    DEVOLUCION_POSTERIOR,
    EXTINTOR,
    BATERIA_1,
    BATERIA_2,
    CONO,
    BOTIQUIN,
    CARGADOR,
    TRANSFORMADOR,
    CABLE_ADICIONAL,
    MESA_RODILLOS,
    ELEVADOR_BATERIA,
    CONECTOR_ADICIONAL
}