-- ============================================================
-- CONTROL DE EQUIPOS DE APILAMIENTO
-- Script de inicialización de base de datos
-- ============================================================

-- Tablas base del sistema

CREATE TABLE IF NOT EXISTS dim_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dim_sedes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    direccion VARCHAR(255),
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dim_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_microsoft VARCHAR(255) NOT NULL UNIQUE,
    correo VARCHAR(255) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    puesto VARCHAR(255),
    area VARCHAR(255),
    empresa VARCHAR(255),
    departamento VARCHAR(255),
    ubicacion VARCHAR(255),
    rol_id BIGINT NOT NULL REFERENCES dim_roles(id),
    sitio_id BIGINT REFERENCES dim_sedes(id),
    ultimo_acceso TIMESTAMP WITH TIME ZONE,
    estado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE,
    fecha_baja TIMESTAMP WITH TIME ZONE,
    usuario_creacion BIGINT,
    usuario_actualizacion BIGINT,
    version INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_usuarios_correo ON dim_usuarios(correo);
CREATE INDEX IF NOT EXISTS idx_usuarios_id_microsoft ON dim_usuarios(id_microsoft);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol_id ON dim_usuarios(rol_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_sitio_id ON dim_usuarios(sitio_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_estado ON dim_usuarios(estado_activo);

-- Seed data: roles por defecto (coincide con Flyway V2)
INSERT INTO dim_roles (nombre, descripcion, usuario_creacion)
VALUES ('Super Admin', 'Acceso total al sistema: configuración, reportes, dashboard, catálogos, campañas, auditoría, monitoreo operativo y gestión de administradores', 1)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO dim_roles (nombre, descripcion, usuario_creacion)
VALUES ('Admin', 'Acceso administrativo: gestión de usuarios, equipos, campañas, PSR/OSR, reportes y dashboard sin acceso a configuración crítica', 1)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO dim_roles (nombre, descripcion, usuario_creacion)
VALUES ('Usuario', 'Acceso operativo básico: registro de equipos, averías, evidencias fotográficas y actualización de estados', 1)
ON CONFLICT (nombre) DO NOTHING;

-- Seed data: usuario Super Admin por defecto
INSERT INTO dim_usuarios (id_microsoft, correo, nombre, rol_id, usuario_creacion)
VALUES ('seed-superadmin', 'admin.powerapps@vanguardfresh.pe', 'Super Admin', 1, 1)
ON CONFLICT (correo) DO NOTHING;
